apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-backend-deployment
  namespace: fintrack
spec:
  selector:
    matchLabels:
      app: fintrack-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: fintrack-backend
    spec:
      containers:
      - name: fintrack-backend
        image: jasvinjames/fintrack-backend-k8s
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 3001
        envFrom:
        - secretRef:
            name: fintrack-backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fintrack-backend-service
spec:
  selector:
    app: fintrack-backend
  ports:
  - name: http
    port: 3001
    targetPort: 3001
