apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintrack-frontend-deployment
  namespace: fintrack
spec:
  selector:
    matchLabels:
      app: fintrack
      tier: frontend
  template:
    metadata:
      labels:
        app: fintrack
        tier: frontend
    spec:
      containers:
      - name: fintrack-frontend
        image: jasvinjames/fintrack-frontend
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fintrack-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: fintrack
    tier: frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    
